#pragma once

#define TAP_CODE_DELAY 5

#define TAPPING_TERM 150
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define FLOW_TAP_TERM 100
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD
#define QUICK_TAP_TERM_PER_KEY

#define CAPS_WORD_IDLE_TIMEOUT 5000

#define LAYER_LOCK_IDLE_TIMEOUT 2000

#define SENTENCE_CASE_TIMEOUT 2000

#define COMBO_ONLY_FROM_LAYER 0
