COMBO_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
UNICODE_COMMON = yes

AUTOCORRECT_ENABLE ?= no
CAPS_WORD_ENABLE ?= yes
CONSOLE_ENABLE ?= no
GRAVE_ESC_ENABLE ?= no
LAYER_LOCK_ENABLE ?= yes
NKRO_ENABLE ?= yes
SPACE_CADET_ENABLE ?= no
TAP_DANCE_ENABLE ?= yes
